#!/bin/bash

NODE=/opt/node/bin/node
APP=/home/pi/peaknode
SERVER_JS_FILE=$APP/app.js
USER=pi
OUT=$APP/nodejs.log

case "$1" in

start)
	echo "starting node: $NODE $SERVER_JS_FILE"
	echo "activity log: $OUT"
	sudo -u $USER $NODE $SERVER_JS_FILE > $OUT 2>$OUT &
	;;

stop)
	killall $NODE
	;;

*)
	echo "usage: $0 (start|stop)"
esac

exit 0
