#!/bin/bash


NODE=node
OUT=nodejs.log

case "$1" in
  live)
    echo "restart server live :8001"
    sudo -u $USER $NODE restart.js > $OUT 2>$OUT &
  ;;
  start)
    echo "activity log: $OUT"
    sudo -u $USER $NODE app.js > $OUT 2>$OUT &
  ;;
  pi)
    $NODE=/opt/node/bin/node
    echo "activity log: $OUT"
    sudo -u $USER $NODE app.js > $OUT 2>$OUT &
  ;;
  stop)
  	sudo -u $USER killall $NODE
	;;
  *)
  	echo "usage: $0 (start|pi|stop)"
esac


exit 0
