#!/bin/bash

case "$1" in

start)
	echo "starting node: $NODE $SERVER_JS_FILE"
	echo "activity log: $OUT"
	sudo -u hugh node app.js > nodejs.log 2> nodejs.log &
	;;

stop)
	killall $NODE
	;;

*)
	echo "usage: $0 (start|stop)"
esac

exit 0
